# Generated by Django 4.1.3 on 2023-02-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('color', models.CharField(max_length=55)),
                ('company', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('type', models.CharField(choices=[('b6', 'B6'), ('b12', 'B12')], default='b6', max_length=20)),
                ('etat', models.CharField(choices=[('b6', 'B6'), ('b12', 'B12')], default='bon', max_length=20)),
                ('number_register', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NewGaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('color', models.CharField(max_length=55)),
                ('company', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('type', models.CharField(choices=[('depot', 'Depot'), ('retrait', 'Retrait'), ('transfert', 'Transfert')], max_length=20)),
                ('number_register', models.CharField(max_length=255)),
            ],
        ),
    ]
