# Generated by Django 4.1.7 on 2023-02-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaz',
            name='image',
            field=models.CharField(default='', max_length=1000000000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gaz',
            name='etat',
            field=models.CharField(choices=[('bon', 'Bon'), ('moyen', 'Moyen'), ('mauvais', 'Mauvais')], default='bon', max_length=20),
        ),
    ]
