# Generated by Django 4.1.7 on 2023-02-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaz', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='nom',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pays',
            field=models.CharField(default="cote d'ivoire", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='vile',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='zipcode',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
