# Generated by Django 4.1.7 on 2023-02-21 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaz', '0005_order_address_order_email_order_nom_order_pays_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='users',
        ),
    ]
