# Generated by Django 4.1.7 on 2023-02-21 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaz', '0006_remove_order_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 18, 59, 25, 907773, tzinfo=datetime.timezone.utc)),
        ),
    ]
