# Generated by Django 4.1.7 on 2023-03-13 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaz', '0010_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='produit',
        ),
        migrations.AddField(
            model_name='commande',
            name='gaz',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gaz.gaz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='newgaz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gaz.newgaz'),
            preserve_default=False,
        ),
    ]
