# Generated by Django 4.1.3 on 2022-12-11 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_posts_alter_post_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='posts',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 0, 22, 11, 205558, tzinfo=datetime.timezone.utc)),
        ),
    ]
