# Generated by Django 4.1.3 on 2022-12-05 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='posts',
            new_name='post',
        ),
    ]
